# Generated by Django 4.1.7 on 2023-03-04 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='btcvalue',
        ),
    ]
